"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestTPEPOO,
	#superclass : #PackageManifest,
	#category : #'TP_POO4-Manifest'
}

{ #category : #'code-critics' }
ManifestTPEPOO class >> ruleRBGlobalVariablesUsageV1FalsePositive [
	^ #(#(#(#RGPackageDefinition #(#TPE_POO4)) #'2020-07-02T23:42:05.851628+02:00') )
]
